#!/usr/bin/perl -w
# This script creates the symlinks needed by this RPM
# Specific support exists to create symlinks within e-smith web "panels"
# and for links from named "events" directories into the "actions" directory

use esmith::Build::CreateLinks qw(:all);
my $event;

panel_link("sarg", 'manager');

for my $event (qw(
    bootstrap-console-save
    sarg-update
    ))
{
    templates2events("/etc/sarg/sarg.conf", $event);
    templates2events("/etc/cron.daily/sarg", $event);
    templates2events("/etc/cron.weekly/sarg", $event);
    templates2events("/etc/cron.monthly/sarg", $event);
}

for  my $event (qw(
     sarg-update
    ))
{
    templates2events("/etc/httpd/conf/httpd.conf", $event);
    safe_symlink("sigusr1", "root/etc/e-smith/events/$event/services2adjust/httpd-e-smith"); 
}

#safe_symlink("/etc/sarg/fonts/","root/usr/share/sarg/");
#safe_symlink("/etc/sarg/languages/","root/usr/share/sarg/");
#safe_symlink("/etc/sarg/images/","root/usr/share/sarg/");
